--// Updated in 9/10/2025 \\--

local list  = {
  ["Minh Hưng"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Kind",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
    ["Quốc An"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Kind",
    ["Hate me"] = "He now, not hate me, and we are best friends!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A1",
  },
  ["Anh Thư"] = {
    ["Age"] = 14,
    ["Boy"] = false,
    ["Girl"] = true,
    ["Health"] = "Quite weak",
    ["Character"] = "Kind",
    ["Hate me"] = "She now, not hate me!",
    ["Neutral"] = "No, she not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
    ["Văn Phú"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Normal",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
    ["Ngọc Dững"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Kind",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
    ["Văn Thái"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Kind",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
  ["Gia Long"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Neutral",
    ["Hate me"] = "He can hating me, but i dont know",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
  ["Thành Luân"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Neutral",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "Yes, he doesn't consider me a friend",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
  ["Thanh Đạt"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Neutral",
    ["Hate me"] = "He now, hate me, but just is near time!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "14 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
  ["Thành Hưng"] = {
    ["Age"] = 14,
    ["Boy"] = true,
    ["Girl"] = false,
    ["Health"] = "Good",
    ["Character"] = "Kind",
    ["Hate me"] = "He now, not hate me!",
    ["Neutral"] = "No, he not have this",
    ["Time-meet"] = "3 years ago",
    ["Class"] = "9A4",
    ["Old Class"] = "9A4",
  },
}
